// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.Search {
	
	
	public partial class QuickSearch {
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
	}
}
