// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.dialogs {
	
	
	public partial class AssignDomain {
		
		protected global::umbraco.uicontrols.Feedback FeedBackMessage;
		
		protected global::umbraco.uicontrols.Pane pane_addnew;
		
		protected global::umbraco.uicontrols.PropertyPanel prop_domain;
		
		protected System.Web.UI.WebControls.TextBox DomainName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator DomainValidator;
		
		protected global::umbraco.uicontrols.PropertyPanel prop_lang;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator LanguageValidator;
		
		protected System.Web.UI.WebControls.DropDownList Languages;
		
		protected System.Web.UI.WebControls.Button ok;
		
		protected global::umbraco.uicontrols.Pane pane_edit;
		
		protected System.Web.UI.WebControls.Literal allDomains;
	}
}
