// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.dialogs {
	
	
	public partial class create {
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden path;
		
		protected global::umbraco.uicontrols.Pane pane_chooseNode;
		
		protected umbraco.controls.Tree.TreeControl JTree;
		
		protected System.Web.UI.WebControls.Panel panel_buttons;
		
		protected global::umbraco.uicontrols.Feedback PageNameHolder;
		
		protected global::umbraco.uicontrols.Pane pane_chooseName;
		
		protected System.Web.UI.WebControls.PlaceHolder phCreate;
	}
}
