// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dialogs {
	
	
	public partial class ExportCode {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected global::umbraco.uicontrols.Pane pane_language;
		
		protected System.Web.UI.WebControls.DropDownList ddlGenerationMode;
		
		protected global::umbraco.uicontrols.Pane pane_contextName;
		
		protected System.Web.UI.WebControls.TextBox txtDataContextName;
		
		protected System.Web.UI.WebControls.TextBox txtNamespace;
		
		protected System.Web.UI.WebControls.Panel pnlButtons;
		
		protected System.Web.UI.WebControls.Button btnGenerate;
		
		protected global::umbraco.uicontrols.Pane pane_files;
		
		protected System.Web.UI.WebControls.HyperLink lnkPoco;
		
		protected System.Web.UI.WebControls.HyperLink lnkAbstractions;
	}
}
