// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dialogs {
	
	
	public partial class mediaPicker {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected global::umbraco.uicontrols.Pane pane_src;
		
		protected global::umbraco.controls.Images.ImageViewer ImageViewer;
		
		protected global::umbraco.uicontrols.TabView tv_options;
		
		protected global::umbraco.uicontrols.Pane pane_select;
		
		protected global::umbraco.controls.Tree.TreeControl DialogTree;
		
		protected System.Web.UI.WebControls.Panel pane_upload;
		
		protected global::umbraco.controls.Images.UploadMediaImage MediaUploader;
	}
}
