// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.dialogs {
	
	
	public partial class moveOrCopy {
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected umbraco.uicontrols.Feedback feedback;
		
		protected umbraco.uicontrols.Pane pane_form;
		
		protected umbraco.controls.Tree.TreeControl JTree;
		
		protected umbraco.uicontrols.PropertyPanel pp_relate;
		
		protected System.Web.UI.WebControls.CheckBox RelateDocuments;
		
		protected System.Web.UI.WebControls.PlaceHolder pane_form_notice;
		
		protected umbraco.uicontrols.Pane pane_settings;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected System.Web.UI.WebControls.ListBox masterType;
		
		protected System.Web.UI.WebControls.TextBox rename;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.Panel panel_buttons;
		
		protected System.Web.UI.WebControls.Button ok;
	}
}
