// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.dialogs {
	
	
	public partial class notifications {
		
		protected global::umbraco.uicontrols.Feedback feedback;
		
		protected global::umbraco.uicontrols.Pane pane_form;
		
		protected System.Web.UI.WebControls.Panel pl_buttons;
		
		protected System.Web.UI.WebControls.Button Button1;
	}
}
