// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dialogs {
	
	
	public partial class protectPage {
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden tempFile;
		
		protected global::umbraco.uicontrols.Feedback feedback;
		
		protected System.Web.UI.WebControls.Panel p_mode;
		
		protected global::umbraco.uicontrols.Pane pane_chooseMode;
		
		protected System.Web.UI.WebControls.RadioButton rb_simple;
		
		protected System.Web.UI.WebControls.RadioButton rb_advanced;
		
		protected System.Web.UI.WebControls.Panel p_noGroupsFound;
		
		protected System.Web.UI.WebControls.Button bt_selectMode;
		
		protected global::umbraco.uicontrols.Pane pane_simple;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_login;
		
		protected System.Web.UI.WebControls.TextBox simpleLogin;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_pass;
		
		protected System.Web.UI.WebControls.TextBox simplePassword;
		
		protected global::umbraco.uicontrols.Pane pane_advanced;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel3;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel2;
		
		protected System.Web.UI.WebControls.PlaceHolder groupsSelector;
		
		protected System.Web.UI.WebControls.Panel p_buttons;
		
		protected global::umbraco.uicontrols.Pane pane_pages;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_loginPage;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_loginpage;
		
		protected System.Web.UI.WebControls.CustomValidator cv_loginPage;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_errorPage;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_errorpage;
		
		protected System.Web.UI.WebControls.CustomValidator cv_errorPage;
		
		protected System.Web.UI.WebControls.Button bt_protect;
		
		protected System.Web.UI.WebControls.Button bt_buttonRemoveProtection;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden errorId;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden loginId;
		
		protected System.Web.UI.WebControls.PlaceHolder js;
	}
}
