// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.dialogs {
	
	
	public partial class RegexWs {
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected global::umbraco.uicontrols.Pane pane1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_search;
		
		protected System.Web.UI.WebControls.TextBox searchField;
		
		protected System.Web.UI.WebControls.Button bt_search;
		
		protected System.Web.UI.WebControls.Panel regexPanel;
		
		protected System.Web.UI.WebControls.Repeater results;
		
		protected System.Web.UI.WebControls.Literal header;
		
		protected System.Web.UI.WebControls.Literal desc;
		
		protected System.Web.UI.WebControls.Literal regex;
	}
}
