// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class republish {
		
		protected System.Web.UI.WebControls.Panel p_republish;
		
		protected System.Web.UI.WebControls.Button bt_go;
		
		protected global::umbraco.uicontrols.ProgressBar progbar;
		
		protected System.Web.UI.WebControls.Panel p_done;
	}
}
