// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.dialogs {
	
	
	public partial class rollBack {
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected global::umbraco.uicontrols.Feedback feedBackMsg;
		
		protected global::umbraco.uicontrols.Pane pp_selectVersion;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_currentVersion;
		
		protected System.Web.UI.WebControls.Literal currentVersionTitle;
		
		protected System.Web.UI.WebControls.Literal currentVersionMeta;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_rollBackTo;
		
		protected System.Web.UI.WebControls.DropDownList allVersions;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_view;
		
		protected System.Web.UI.WebControls.RadioButtonList rbl_mode;
		
		protected System.Web.UI.WebControls.Panel diffPanel;
		
		protected System.Web.UI.WebControls.Literal lt_notice;
		
		protected System.Web.UI.WebControls.Literal propertiesCompare;
		
		protected System.Web.UI.WebControls.Button doRollback;
	}
}
