// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.dialogs {
	
	
	public partial class search {
		
		protected System.Web.UI.WebControls.Content header1;
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected global::umbraco.uicontrols.Pane Wizard;
		
		protected System.Web.UI.WebControls.TextBox keyword;
		
		protected System.Web.UI.WebControls.Button searchButton;
		
		protected System.Web.UI.WebControls.Panel nothingFound;
		
		protected System.Web.UI.WebControls.Xml searchResult;
		
		protected System.Web.UI.WebControls.Content footer1;
	}
}
