// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.dialogs {
	
	
	public partial class sendToTranslation {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected global::umbraco.uicontrols.Feedback feedback;
		
		protected global::umbraco.uicontrols.Pane pane_form;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_translator;
		
		protected System.Web.UI.WebControls.DropDownList translator;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_language;
		
		protected System.Web.UI.WebControls.DropDownList language;
		
		protected System.Web.UI.WebControls.Literal defaultLanguage;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_includeSubs;
		
		protected System.Web.UI.WebControls.CheckBox includeSubpages;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_comment;
		
		protected System.Web.UI.WebControls.TextBox comment;
		
		protected System.Web.UI.WebControls.Panel pl_buttons;
		
		protected System.Web.UI.WebControls.Button doTranslation;
	}
}
