// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class sort {
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected global::umbraco.uicontrols.ProgressBar prog1;
		
		protected System.Web.UI.WebControls.Literal sortDone;
		
		protected global::umbraco.uicontrols.Pane sortPane;
		
		protected System.Web.UI.WebControls.Literal lt_nodes;
	}
}
