// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dialogs {
	
	
	public partial class viewAuditTrail {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude2;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude3;
		
		protected System.Web.UI.WebControls.DataGrid auditLog;
	}
}
