// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.controls.Tree {
	
	
	public partial class TreeControl {
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude2;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude3;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude4;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude5;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude6;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude8;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude11;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude7;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude12;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude9;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude10;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TreeContainer;
	}
}
