// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.developer {
	
	
	public partial class editXslt {
		
		protected System.Web.UI.WebControls.Content cp2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected System.Web.UI.WebControls.Content cp1;
		
		protected global::umbraco.uicontrols.UmbracoPanel UmbracoPanel1;
		
		protected global::umbraco.uicontrols.Pane Pane1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_filename;
		
		protected System.Web.UI.WebControls.TextBox xsltFileName;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_testing;
		
		protected System.Web.UI.WebControls.CheckBox SkipTesting;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_errorMsg;
		
		protected global::umbraco.uicontrols.CodeArea editorSource;
		
		protected System.Web.UI.WebControls.Literal editorJs;
	}
}
