// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.user {
	
	
	public partial class EditUserType {
		
		protected global::umbraco.uicontrols.UmbracoPanel pnlUmbraco;
		
		protected global::umbraco.uicontrols.Pane pnl1;
		
		protected System.Web.UI.WebControls.HiddenField hidUserTypeID;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.TextBox txtUserTypeName;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_alias;
		
		protected System.Web.UI.WebControls.Label lblUserTypeAlias;
		
		protected global::umbraco.uicontrols.Pane pnl2;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_rights;
		
		protected System.Web.UI.WebControls.CheckBoxList cbl_rights;
	}
}
