// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.user {
	
	
	public partial class PermissionEditor {
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude2;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected umbraco.uicontrols.UmbracoPanel pnlUmbraco;
		
		protected umbraco.uicontrols.Pane pnl1;
		
		protected umbraco.controls.Tree.TreeControl JTree;
		
		protected umbraco.cms.presentation.user.NodePermissions nodePermissions;
	}
}
