// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dashboard.Settings {
	
	
	public partial class Applyskin {
		
		protected System.Web.UI.WebControls.DropDownList skinpicker;
		
		protected System.Web.UI.WebControls.Button bt_apply;
		
		protected System.Web.UI.WebControls.Button bt_rollback;
	}
}
