// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.translation {
	
	
	public partial class _default {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel2;
		
		protected global::umbraco.uicontrols.Feedback feedback;
		
		protected global::umbraco.uicontrols.Pane pane_uploadFile;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile translationFile;
		
		protected System.Web.UI.WebControls.Button uploadFile;
		
		protected global::umbraco.uicontrols.Pane pane_tasks;
		
		protected System.Web.UI.WebControls.Literal lt_tasksHelp;
		
		protected System.Web.UI.WebControls.GridView taskList;
	}
}
