// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.translation {
	
	
	public partial class details {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected global::umbraco.uicontrols.UmbracoPanel panel1;
		
		protected global::umbraco.uicontrols.Pane pane_details;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_date;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_owner;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_totalWords;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_comment;
		
		protected global::umbraco.uicontrols.Pane pane_tasks;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_xml;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_upload;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_closeTask;
		
		protected System.Web.UI.WebControls.Button bt_close;
		
		protected global::umbraco.uicontrols.Pane pane_fields;
		
		protected System.Web.UI.WebControls.DataGrid dg_fields;
		
		protected System.Web.UI.WebControls.Content Content3;
	}
}
