// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.actions {
	
	
	public partial class delete {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel2;
		
		protected System.Web.UI.WebControls.Panel confirm;
		
		protected global::umbraco.uicontrols.Pane pane_delete;
		
		protected System.Web.UI.WebControls.Literal warning;
		
		protected System.Web.UI.WebControls.Button deleteButton;
		
		protected global::umbraco.uicontrols.Pane deleteMessage;
		
		protected System.Web.UI.WebControls.Literal deleted;
	}
}
