// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.create.controls {
	
	
	public partial class member {
		
		protected System.Web.UI.WebControls.ValidationSummary validationSummary;
		
		protected System.Web.UI.WebControls.Literal nameLiteral;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator nameRequired;
		
		protected System.Web.UI.WebControls.TextBox rename;
		
		protected System.Web.UI.WebControls.Panel memberChooser;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator memberTypeRequired;
		
		protected System.Web.UI.WebControls.ListBox nodeType;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator loginRequired;
		
		protected System.Web.UI.WebControls.CustomValidator loginExistsCheck;
		
		protected System.Web.UI.WebControls.TextBox Login;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator emailRequired;
		
		protected System.Web.UI.WebControls.CustomValidator emailExistsCheck;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.Literal PasswordRules;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator passwordRequired;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.TextBox Textbox1;
		
		protected System.Web.UI.WebControls.Button sbmt;
	}
}
