// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.create.controls {
	
	
	public partial class nodeType {
		
		protected System.Web.UI.WebControls.ListBox masterType;
		
		protected System.Web.UI.WebControls.Literal masterTypePreDefined;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidation1;
		
		protected System.Web.UI.WebControls.TextBox rename;
		
		protected System.Web.UI.WebControls.CheckBox createTemplate;
		
		protected System.Web.UI.WebControls.TextBox Textbox1;
		
		protected System.Web.UI.WebControls.Button sbmt;
	}
}
