// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.create {
	
	
	public partial class xslt {
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox rename;
		
		protected System.Web.UI.WebControls.ListBox xsltTemplate;
		
		protected System.Web.UI.WebControls.CheckBox createMacro;
		
		protected System.Web.UI.WebControls.TextBox Textbox1;
		
		protected System.Web.UI.WebControls.Button sbmt;
	}
}
