// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.controls {
	
	
	public partial class ContentTypeControlNew {
		
		protected global::umbraco.uicontrols.TabView TabView1;
		
		protected System.Web.UI.WebControls.Panel pnlGeneral;
		
		protected System.Web.UI.WebControls.Panel pnlTab;
		
		protected global::umbraco.uicontrols.Pane PaneTabsInherited;
		
		protected System.Web.UI.WebControls.Literal tabsMasterContentTypeName;
		
		protected global::umbraco.uicontrols.Pane Pane2;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_newTab;
		
		protected System.Web.UI.WebControls.TextBox txtNewTab;
		
		protected System.Web.UI.WebControls.Button btnNewTab;
		
		protected global::umbraco.uicontrols.Pane Pane1;
		
		protected System.Web.UI.WebControls.DataGrid dgTabs;
		
		protected System.Web.UI.WebControls.TextBox txtTab;
		
		protected System.Web.UI.WebControls.TextBox txtSortOrder;
		
		protected System.Web.UI.WebControls.Literal lttNoTabs;
		
		protected System.Web.UI.WebControls.Panel pnlInfo;
		
		protected global::umbraco.uicontrols.Pane Pane3;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_alias;
		
		protected System.Web.UI.WebControls.TextBox txtAlias;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_icon;
		
		protected System.Web.UI.WebControls.DropDownList ddlIcons;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_thumbnail;
		
		protected System.Web.UI.WebControls.DropDownList ddlThumbnails;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_description;
		
		protected System.Web.UI.WebControls.TextBox description;
		
		protected System.Web.UI.WebControls.Panel pnlStructure;
		
		protected global::umbraco.uicontrols.Pane Pane5;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_allowedChildren;
		
		protected System.Web.UI.WebControls.CheckBoxList lstAllowedContentTypes;
		
		protected System.Web.UI.WebControls.PlaceHolder PlaceHolderAllowedContentTypes;
		
		protected System.Web.UI.WebControls.Panel pnlProperties;
		
		protected global::umbraco.uicontrols.Pane PanePropertiesInherited;
		
		protected System.Web.UI.WebControls.Literal propertiesMasterContentTypeName;
		
		protected global::umbraco.uicontrols.Pane Pane4;
		
		protected System.Web.UI.WebControls.PlaceHolder PropertyTypeNew;
		
		protected System.Web.UI.WebControls.PlaceHolder PropertyTypes;
		
		protected System.Web.UI.WebControls.Literal theClientId;
	}
}
