// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.settings {
	
	
	public partial class EditContentTypeNew {
		
		protected global::umbraco.uicontrols.Pane tmpPane;
		
		protected global::umbraco.uicontrols.PropertyPanel pp1;
		
		protected System.Web.UI.WebControls.CheckBoxList templateList;
		
		protected global::umbraco.uicontrols.PropertyPanel pp2;
		
		protected System.Web.UI.WebControls.DropDownList ddlTemplates;
	}
}
