// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.settings {
	
	
	public partial class editLanguage {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Pane Pane7;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_language;
		
		protected System.Web.UI.WebControls.DropDownList Cultures;
	}
}
