// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.developer {
	
	
	public partial class editDatatype {
		
		protected umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected umbraco.uicontrols.Pane pane_control;
		
		protected umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.TextBox txtName;
		
		protected umbraco.uicontrols.PropertyPanel pp_renderControl;
		
		protected System.Web.UI.WebControls.DropDownList ddlRenderControl;
		
		protected umbraco.uicontrols.PropertyPanel pp_guid;
		
		protected System.Web.UI.WebControls.Literal litGuid;
		
		protected umbraco.uicontrols.Pane pane_settings;
		
		protected System.Web.UI.WebControls.PlaceHolder plcEditorPrevalueControl;
	}
}
