// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.plugins.tinymce3 {
	
	
	public partial class insertLink {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected global::umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude4;
		
		protected global::umbraco.uicontrols.Pane pane_url;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel2;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel3;
		
		protected global::umbraco.uicontrols.TabView tv_options;
		
		protected global::umbraco.uicontrols.Pane pane_content;
		
		protected global::umbraco.controls.Tree.TreeControl TreeControl2;
		
		protected global::umbraco.uicontrols.Pane pane_media;
		
		protected global::umbraco.controls.Tree.TreeControl TreeControl1;
	}
}
