// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.plugins.tinymce3 {
	
	
	public partial class InsertAnchor {
		
		protected global::umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude4;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
	}
}
