// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.plugins.tinymce3 {
	
	
	public partial class insertImage {
		
		protected global::umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude9;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude8;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude4;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude5;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude6;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude7;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected global::umbraco.uicontrols.Pane pane_src;
		
		protected global::umbraco.controls.Images.ImageViewer ImageViewer;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_src;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_title;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_dimensions;
		
		protected System.Web.UI.WebControls.Literal lt_widthLabel;
		
		protected System.Web.UI.WebControls.Literal lt_heightLabel;
		
		protected global::umbraco.uicontrols.TabView tv_options;
		
		protected global::umbraco.uicontrols.Pane pane_select;
		
		protected global::umbraco.controls.Tree.TreeControl DialogTree;
		
		protected System.Web.UI.WebControls.Panel pane_upload;
		
		protected global::umbraco.controls.Images.UploadMediaImage MediaUploader;
	}
}
