// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.developer {
	
	
	public partial class editPython {
		
		protected System.Web.UI.WebControls.Content cp0;
		
		protected System.Web.UI.WebControls.Content cp1;
		
		protected umbraco.uicontrols.UmbracoPanel UmbracoPanel1;
		
		protected umbraco.uicontrols.Pane Pane1;
		
		protected umbraco.uicontrols.PropertyPanel pp_filename;
		
		protected System.Web.UI.WebControls.TextBox pythonFileName;
		
		protected umbraco.uicontrols.PropertyPanel pp_testing;
		
		protected System.Web.UI.WebControls.CheckBox SkipTesting;
		
		protected umbraco.uicontrols.PropertyPanel pp_errorMsg;
		
		protected umbraco.uicontrols.CodeArea pythonSource;
	}
}
