// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class dashboard {
		
		protected System.Web.UI.WebControls.Content ContentBody;
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel2;
		
		protected System.Web.UI.WebControls.PlaceHolder dashBoardContent;
		
		protected global::umbraco.uicontrols.TabView dashboardTabs;
	}
}
