// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class login {
		
		protected umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected System.Web.UI.WebControls.Literal TopText;
		
		protected System.Web.UI.WebControls.Label username;
		
		protected System.Web.UI.WebControls.TextBox lname;
		
		protected System.Web.UI.WebControls.Label password;
		
		protected System.Web.UI.WebControls.TextBox passw;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Literal BottomText;
		
		protected System.Web.UI.WebControls.HiddenField hf_height;
		
		protected System.Web.UI.WebControls.HiddenField hf_width;
		
		protected System.Web.UI.WebControls.PlaceHolder loginError;
	}
}
