// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class test {
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.ScriptManager scriptmanager;
		
		protected System.Web.UI.WebControls.PlaceHolder testHolder;
		
		protected System.Web.UI.WebControls.Button button;
		
		protected System.Web.UI.WebControls.PlaceHolder result;
	}
}
