// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class TreeInit {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected global::umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected umbraco.controls.Tree.TreeControl JTree;
	}
}
