// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
	
	
	public partial class _umbraco {
		
		protected global::umbraco.uicontrols.UmbracoClientDependencyLoader ClientLoader;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude1;
		
		protected ClientDependency.Core.Controls.CssInclude CssInclude2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude3;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude14;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude5;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude6;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude13;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude7;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude8;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude9;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude10;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude11;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude4;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude17;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude12;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude15;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude16;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.ScriptManager umbracoScriptManager;
		
		protected System.Web.UI.WebControls.Panel FindDocuments;
		
		protected umbraco.presentation.Search.QuickSearch Search;
		
		protected global::umbraco.uicontrols.UmbracoPanel treeWindow;
		
		protected umbraco.controls.Tree.TreeControl JTree;
		
		protected global::umbraco.uicontrols.UmbracoPanel PlaceHolderAppIcons;
		
		protected System.Web.UI.WebControls.Literal plcIcons;
	}
}
