// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.dashboard {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Panel changeForm;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude2;
		
		protected System.Web.UI.WebControls.Panel errorPane;
		
		protected System.Web.UI.WebControls.Literal errorMessage;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label passwordLabel;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator passwordvalidator;
		
		protected System.Web.UI.WebControls.Label confirmpasswordlabel;
		
		protected System.Web.UI.WebControls.TextBox confirmpassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator confirmpasswordvalidator;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.WebControls.Button changePassword;
		
		protected System.Web.UI.WebControls.Panel passwordChanged;
	}
}
