// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.developer.packages {
	
	
	public partial class _Default {
		
		protected global::umbraco.uicontrols.TabView TabView1;
		
		protected global::umbraco.uicontrols.Pane Pane1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.TextBox packageName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator0;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_url;
		
		protected System.Web.UI.WebControls.TextBox packageUrl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_version;
		
		protected System.Web.UI.WebControls.TextBox packageVersion;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_file;
		
		protected System.Web.UI.WebControls.Button bt_submitButton;
		
		protected System.Web.UI.WebControls.Literal packageUmbFile;
		
		protected global::umbraco.uicontrols.Pane Pane1_1;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_author;
		
		protected System.Web.UI.WebControls.TextBox packageAuthorName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_author_url;
		
		protected System.Web.UI.WebControls.TextBox packageAuthorUrl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected global::umbraco.uicontrols.Pane Pane1_2;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_licens;
		
		protected System.Web.UI.WebControls.TextBox packageLicenseName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_license_url;
		
		protected System.Web.UI.WebControls.TextBox packageLicenseUrl;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
		
		protected global::umbraco.uicontrols.Pane Pane1_3;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_readme;
		
		protected System.Web.UI.WebControls.TextBox packageReadme;
		
		protected global::umbraco.uicontrols.Pane Pane2;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_content;
		
		protected System.Web.UI.WebControls.PlaceHolder content;
		
		protected System.Web.UI.WebControls.CheckBox packageContentSubdirs;
		
		protected global::umbraco.uicontrols.Pane Pane2_1;
		
		protected System.Web.UI.WebControls.CheckBoxList documentTypes;
		
		protected global::umbraco.uicontrols.Pane Pane2_2;
		
		protected System.Web.UI.WebControls.CheckBoxList templates;
		
		protected global::umbraco.uicontrols.Pane Pane2_3;
		
		protected System.Web.UI.WebControls.CheckBoxList stylesheets;
		
		protected global::umbraco.uicontrols.Pane Pane2_4;
		
		protected System.Web.UI.WebControls.CheckBoxList macros;
		
		protected global::umbraco.uicontrols.Pane Pane2_5;
		
		protected System.Web.UI.WebControls.CheckBoxList languages;
		
		protected global::umbraco.uicontrols.Pane Pane2_6;
		
		protected System.Web.UI.WebControls.CheckBoxList dictionary;
		
		protected global::umbraco.uicontrols.Pane Pane2_7;
		
		protected System.Web.UI.WebControls.CheckBoxList cbl_datatypes;
		
		protected global::umbraco.uicontrols.Pane Pane3;
		
		protected global::umbraco.uicontrols.Pane Pane3_1;
		
		protected System.Web.UI.WebControls.Repeater packageFilesRepeater;
		
		protected System.Web.UI.WebControls.TextBox packageFilePath;
		
		protected System.Web.UI.WebControls.Button delete;
		
		protected System.Web.UI.WebControls.TextBox packageFilePathNew;
		
		protected System.Web.UI.WebControls.Button createNewFilePath;
		
		protected global::umbraco.uicontrols.Pane Pane3_2;
		
		protected System.Web.UI.WebControls.TextBox packageControlPath;
		
		protected global::umbraco.uicontrols.Pane Pane4;
		
		protected System.Web.UI.WebControls.CustomValidator actionsVal;
		
		protected System.Web.UI.WebControls.TextBox tb_actions;
	}
}
