// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.developer.packages {
	
	
	public partial class Installer {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Feedback fb;
		
		protected global::umbraco.uicontrols.Pane pane_upload;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel9;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile file1;
		
		protected System.Web.UI.WebControls.Button ButtonLoadPackage;
		
		protected global::umbraco.uicontrols.ProgressBar progbar1;
		
		protected global::umbraco.uicontrols.Pane pane_authenticate;
		
		protected System.Web.UI.WebControls.TextBox tb_email;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected System.Web.UI.WebControls.TextBox tb_password;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel2;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Panel pane_acceptLicense;
		
		protected global::umbraco.uicontrols.Pane pane_acceptLicenseInner;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel3;
		
		protected System.Web.UI.WebControls.Label LabelName;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel5;
		
		protected System.Web.UI.WebControls.Label LabelAuthor;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel4;
		
		protected System.Web.UI.WebControls.Label LabelMore;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel6;
		
		protected System.Web.UI.WebControls.Label LabelLicense;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel7;
		
		protected System.Web.UI.WebControls.CheckBox acceptCheckbox;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel8;
		
		protected System.Web.UI.WebControls.Literal readme;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_unsecureFiles;
		
		protected System.Web.UI.WebControls.Literal lt_files;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_macroConflicts;
		
		protected System.Web.UI.WebControls.Literal ltrMacroAlias;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_templateConflicts;
		
		protected System.Web.UI.WebControls.Literal ltrTemplateAlias;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_stylesheetConflicts;
		
		protected System.Web.UI.WebControls.Literal ltrStylesheetNames;
		
		protected global::umbraco.uicontrols.ProgressBar _progbar1;
		
		protected System.Web.UI.WebControls.Button ButtonInstall;
		
		protected global::umbraco.uicontrols.Pane pane_installing;
		
		protected global::umbraco.uicontrols.ProgressBar progBar2;
		
		protected System.Web.UI.WebControls.Literal lit_installStatus;
		
		protected global::umbraco.uicontrols.Pane pane_optional;
		
		protected global::umbraco.uicontrols.Pane pane_success;
		
		protected System.Web.UI.WebControls.Button bt_viewInstalledPackage;
		
		protected System.Web.UI.WebControls.Literal lit_authorUrl;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden tempFile;
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden processState;
	}
}
