// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.developer.packages {
	
	
	public partial class installedPackage {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected System.Web.UI.WebControls.Panel packageUninstalled;
		
		protected global::umbraco.uicontrols.Pane pane_uninstalled;
		
		protected System.Web.UI.WebControls.Panel installedPackagePanel;
		
		protected global::umbraco.uicontrols.Pane pane_meta;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.Literal lt_packagename;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_version;
		
		protected System.Web.UI.WebControls.Literal lt_packageVersion;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_author;
		
		protected System.Web.UI.WebControls.Literal lt_packageAuthor;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_documentation;
		
		protected System.Web.UI.WebControls.HyperLink hl_docLink;
		
		protected System.Web.UI.WebControls.LinkButton lb_demoLink;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_repository;
		
		protected System.Web.UI.WebControls.HyperLink hl_packageRepo;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_readme;
		
		protected System.Web.UI.WebControls.Literal lt_readme;
		
		protected global::umbraco.uicontrols.Pane pane_options;
		
		protected System.Web.UI.WebControls.Literal lt_noUpdate;
		
		protected System.Web.UI.WebControls.Button bt_update;
		
		protected System.Web.UI.WebControls.Button bt_uninstall;
		
		protected global::umbraco.uicontrols.Pane pane_noItems;
		
		protected System.Web.UI.WebControls.Button bt_deletePackage;
		
		protected global::umbraco.uicontrols.Pane pane_upgrade;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_upgradeInstruction;
		
		protected System.Web.UI.WebControls.Literal lt_upgradeReadme;
		
		protected System.Web.UI.WebControls.Button bt_gotoUpgrade;
		
		protected global::umbraco.uicontrols.Pane pane_uninstall;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_docTypes;
		
		protected System.Web.UI.WebControls.CheckBoxList documentTypes;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_templates;
		
		protected System.Web.UI.WebControls.CheckBoxList templates;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_css;
		
		protected System.Web.UI.WebControls.CheckBoxList stylesheets;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_macros;
		
		protected System.Web.UI.WebControls.CheckBoxList macros;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_files;
		
		protected System.Web.UI.WebControls.CheckBoxList files;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_di;
		
		protected System.Web.UI.WebControls.CheckBoxList dictionaryItems;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_dt;
		
		protected System.Web.UI.WebControls.CheckBoxList dataTypes;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_confirm;
		
		protected System.Web.UI.WebControls.Button bt_confirmUninstall;
		
		protected global::umbraco.uicontrols.ProgressBar progbar;
	}
}
