// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.developer.packages {
	
	
	public partial class LoadNitros {
		
		protected System.Web.UI.WebControls.Panel loadNitros;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_recommendedHolder;
		
		protected System.Web.UI.WebControls.Repeater rep_nitros;
		
		protected System.Web.UI.WebControls.Literal lit_name;
		
		protected System.Web.UI.WebControls.Literal lit_desc;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_nitroHolder;
		
		protected System.Web.UI.WebControls.Button bt_install;
	}
}
