// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.developer.Packages {
	
	
	public partial class StarterKits {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected ClientDependency.Core.Controls.JsInclude JsInclude1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Feedback fb;
		
		protected global::umbraco.uicontrols.Pane StarterKitInstalled;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_skins;
		
		protected global::umbraco.uicontrols.Pane StarterKitNotInstalled;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_starterkits;
		
		protected global::umbraco.uicontrols.Pane installationCompleted;
	}
}
