// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.developer.packages {
	
	
	public partial class SubmitPackage {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Feedback fb_feedback;
		
		protected System.Web.UI.WebControls.PlaceHolder feedbackControls;
		
		protected global::umbraco.uicontrols.Pane Pane2;
		
		protected System.Web.UI.WebControls.Panel pl_repoChoose;
		
		protected System.Web.UI.WebControls.DropDownList dd_repositories;
		
		protected System.Web.UI.WebControls.Panel pl_repoLogin;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl publicRepoHelp;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl privateRepoHelp;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel2;
		
		protected System.Web.UI.WebControls.TextBox tb_email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel3;
		
		protected System.Web.UI.WebControls.TextBox tb_password;
		
		protected global::umbraco.uicontrols.Pane Pane1;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel4;
		
		protected global::umbraco.uicontrols.PropertyPanel PropertyPanel5;
		
		protected System.Web.UI.WebControls.FileUpload fu_doc;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator doc_regex;
		
		protected System.Web.UI.WebControls.PlaceHolder submitControls;
		
		protected System.Web.UI.WebControls.Button bt_submit;
	}
}
