// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.members {
	
	
	public partial class EditMemberGroup {
		
		protected System.Web.UI.HtmlControls.HtmlInputHidden memberGroupName;
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Pane Pane7;
		
		protected System.Web.UI.WebControls.TextBox NameTxt;
	}
}
