// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.members {
	
	
	public partial class EditMemberType {
		
		protected umbraco.uicontrols.Pane Pane1andmore;
		
		protected System.Web.UI.WebControls.DataGrid dgEditExtras;
		
		protected System.Web.UI.WebControls.CheckBox ckbMemberCanEdit;
		
		protected System.Web.UI.WebControls.CheckBox ckbMemberCanView;
	}
}
