// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.controls.GenericProperties {
	
	
	public partial class GenericProperty {
		
		protected System.Web.UI.WebControls.ImageButton DeleteButton2;
		
		protected System.Web.UI.WebControls.Literal FullHeader;
		
		protected System.Web.UI.WebControls.ImageButton DeleteButton;
		
		protected System.Web.UI.WebControls.Literal Header;
		
		protected System.Web.UI.WebControls.TextBox tbName;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel1;
		
		protected System.Web.UI.WebControls.TextBox tbAlias;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel2;
		
		protected System.Web.UI.WebControls.DropDownList ddlTypes;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel3;
		
		protected System.Web.UI.WebControls.DropDownList ddlTab;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel4;
		
		protected System.Web.UI.WebControls.CheckBox checkMandatory;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel5;
		
		protected System.Web.UI.WebControls.TextBox tbValidation;
		
		protected System.Web.UI.WebControls.HyperLink validationLink;
		
		protected umbraco.uicontrols.PropertyPanel PropertyPanel6;
		
		protected System.Web.UI.WebControls.TextBox tbDescription;
	}
}
