// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.cms.presentation.settings.stylesheet {
	
	
	public partial class editstylesheet {
		
		protected global::umbraco.uicontrols.UmbracoPanel Panel1;
		
		protected global::umbraco.uicontrols.Pane Pane7;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_name;
		
		protected System.Web.UI.WebControls.TextBox NameTxt;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_path;
		
		protected System.Web.UI.WebControls.Literal lttPath;
		
		protected global::umbraco.uicontrols.PropertyPanel pp_source;
		
		protected global::umbraco.uicontrols.CodeArea editorSource;
	}
}
