// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.developer {
	
	
	public partial class assemblyBrowser {
		
		protected System.Web.UI.WebControls.Label AssemblyName;
		
		protected System.Web.UI.WebControls.Panel ChooseProperties;
		
		protected System.Web.UI.WebControls.CheckBoxList MacroProperties;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Panel ConfigProperties;
		
		protected System.Web.UI.WebControls.Literal resultLiteral;
	}
}
