// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.install.steps {
	
	
	public partial class renaming {
		
		protected System.Web.UI.WebControls.Panel init;
		
		protected System.Web.UI.WebControls.Panel noChangedNeeded;
		
		protected System.Web.UI.WebControls.Panel changesNeeded;
		
		protected System.Web.UI.WebControls.Literal identifyResult;
		
		protected System.Web.UI.WebControls.Button updateChanges;
		
		protected System.Web.UI.WebControls.Panel result;
		
		protected System.Web.UI.WebControls.Literal resultText;
	}
}
