// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.install.steps {
	
	
	public partial class validatePermissions {
		
		protected System.Web.UI.WebControls.Literal perfect;
		
		protected System.Web.UI.WebControls.Literal noPackages;
		
		protected System.Web.UI.WebControls.Literal noFolders;
		
		protected System.Web.UI.WebControls.Literal error;
		
		protected System.Web.UI.WebControls.Panel howtoResolve;
		
		protected System.Web.UI.WebControls.Panel grant;
		
		protected System.Web.UI.WebControls.Literal permSummary;
		
		protected System.Web.UI.WebControls.Panel folderWoes;
		
		protected System.Web.UI.WebControls.Literal permissionResults;
		
		protected System.Web.UI.WebControls.Literal packageResults;
		
		protected System.Web.UI.WebControls.Literal xmlResult;
		
		protected System.Web.UI.WebControls.Literal foldersResult;
		
		protected System.Web.UI.WebControls.LinkButton btnNext;
	}
}
