// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace umbraco.presentation.install {
	
	
	public partial class welcome {
		
		protected System.Web.UI.WebControls.PlaceHolder ph_install;
		
		protected System.Web.UI.WebControls.PlaceHolder ph_upgrade;
		
		protected System.Web.UI.WebControls.LinkButton btnNext;
	}
}
